[package]
name = "lxlake-editor"
description = "框架侧应用：只启用 2D UI 渲染（ui-render 档），不编 3D"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
lxlake = { workspace = true, features = ["ui-render"] }